nelmio_api_doc:
    documentation:
        info:
            title: User Data API
            description: API for user creation and user listing.
            version: 1.0.0
    models:
        names:
            -
                alias: UserListItem
                type: App\Document\User
                groups: [user:list]
                areas: [default]
    areas:
        default:
            path_patterns:
                - ^/api(?!/doc$)
